# Site settings
title: ramblings
tagline: scholarly and otherwise
email: teacherjanelle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hands on keyboard. Write. Sometimes badly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: teacherjanelle
github_username:  teacherjanelle

# Build settings
markdown: kramdown



